name: Deploy To Heroku
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_email: '${{secrets.HEROKU_EMAIL}}'
          heroku_api_key: '${{secrets.HEROKU_API_KEY}}'
          heroku_app_name: '${{secrets.HEROKU_APP_NAME}}'
          procfile: 'web: npm run build && npm run start:prod'
